Build with package and config from version.yaml

diff --git a/.github/workflows/openwrt-osm-ci.yml b/.github/workflows/openwrt-osm-ci.yml
--- a/.github/workflows/openwrt-osm-ci.yml
+++ b/.github/workflows/openwrt-osm-ci.yml
@@ -46,25 +46,43 @@ jobs:
           sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint clang bison g++ g++-multilib libncurses-dev python3-distutils rsync file wget
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean
+          echo "======================="
+          echo "Space usage:"
+          echo "======================="
+          df -h
+          echo "======================="
+          du -h ./ --max-depth=1
           
       - name: Download source code
         run: |
+          #Prepare version
+          source ../parse_yaml.sh
+          eval $(parse_yaml ../version.yaml)
+          
+          #Download source code
           rm -f .gitkeep
+          git config --global advice.detachedHead false
+          git clone -b $version_upstream_version_tag --depth 1 https://github.com/openwrt/openwrt.git .
           
-          git -c advice.detachedHead=false clone -b ${{ github.ref_name }} --depth 1 https://github.com/openwrt/openwrt.git .
-          
-          # S1 Repo url
-          # $2 Repo subdirectory (optional)
-          download_package_latest_tag_from_repo(){
-          	latest_tag=$(git ls-remote --tags --refs --sort="v:refname" $1 | tail -n1 | sed 's/.*\///')
-          	echo Download $1@$latest_tag
-          	git -c advice.detachedHead=false -C /tmp clone -b $latest_tag --depth 1 $1
-          	cp -r /tmp/$(basename $1 .git)/$2 package
-          	rm -rf /tmp/$(basename $1 .git)
+          # S1 repo url
+          download_package(){
+          	repo=$(echo $1 | grep -Eo '^http*.*..git')
+          	commit=$(echo $1 | grep -Eo '\^.*' | tr -d '^')
+          	branch=$(echo $1 | grep -Eo ';.*' | tr -d ';')
+          	if [ ! -z $commit ]; then
+          		echo Downloading package from $1
+          		git -C package clone $repo && cd package/$(basename $repo .git) && git checkout $commit && cd -
+          	elif [ ! -z $branch ]; then
+          		echo Downloading package from $1
+          		git -C package clone $repo --depth 1 --branch $branch
+          	else
+          		echo "Invalid package info $1"
+          		exit 1
+          	fi
           }
           
-          download_package_latest_tag_from_repo https://github.com/vernesong/OpenClash.git luci-app-openclash
-          download_package_latest_tag_from_repo https://github.com/jerrykuku/luci-theme-argon.git
+          #Download extra package
+          for f in $version_package_ ; do eval download_package \$${f} ; done
           
       - name: Update feeds
         run: |
@@ -73,37 +91,37 @@ jobs:
 
       - name: Generate configuration file
         run: |
-          VERSION_REPO=$(grep -E '^VERSION_REPO.*https:/.' include/version.mk | grep -Eo 'https://.*[^)]')
-          wget -nv -O .config $VERSION_REPO/targets/x86/64/config.buildinfo
+          #Download upstream release config
+          version_repo=$(grep -E '^VERSION_REPO.*https:/.' include/version.mk | grep -Eo 'https://.*[^)]')
+          wget -nv -O .config $version_repo/targets/x86/64/config.buildinfo
           
-          cat >>.config<<EOF
-          CONFIG_LUCI_LANG_zh_Hans=y
-          CONFIG_PACKAGE_dockerd=y
-          CONFIG_PACKAGE_luci-app-dockerman=y
-          CONFIG_PACKAGE_luci-app-openclash=y
-          CONFIG_PACKAGE_luci-app-smartdns=y
-          CONFIG_PACKAGE_luci-app-sqm=y
-          CONFIG_PACKAGE_luci-app-udpxy=y
-          CONFIG_PACKAGE_luci-app-wireguard=y
-          CONFIG_PACKAGE_kmod-bnx2x=y
-          CONFIG_TARGET_ROOTFS_PARTSIZE=4096
-          EOF
+          #Merge config
+          for f in $version_config_ ; do eval echo \$${f} >> .config ; done
           
           #Set dnsmasq-full as default
           sed -i 's/dnsmasq \\/dnsmasq-full \\/g' include/target.mk
+          #config luci-theme-argon as default theme
           sed -i 's/luci-theme-bootstrap/luci-theme-argon/g' .config
+          #Config version info
           sed -i "s/CONFIG_VERSION_DIST=\"OpenWrt\"/CONFIG_VERSION_DIST=\"OpenWrt-OSM\"/g" .config
+          sed -i "s/CONFIG_VERSION_NUMBER=\"\"/CONFIG_VERSION_NUMBER=\"${version_version_number}\"/g" .config
+          sed -i "s/CONFIG_VERSION_CODE=\"\"/CONFIG_VERSION_CODE=\"$(git -C ../ rev-parse --short=10 HEAD)\"/g" .config
           
           #Download Toolchain
-          wget -nv -O /tmp/release_page.html ${VERSION_REPO}/targets/x86/64/
-          TOOLCHAIN=$(grep -m 1 -Eo '"openwrt-toolchain-(.*).tar.xz"' /tmp/release_page.html | tr -d '"')
-          wget -nv -O /tmp/${TOOLCHAIN} ${VERSION_REPO}/targets/x86/64/${TOOLCHAIN}
-          tar -C /tmp -xf /tmp/${TOOLCHAIN}
-          TOOLCHAIN_DIR_NAME=$(basename $(find /tmp/$(basename $TOOLCHAIN .tar.xz) -name "toolchain-*" -type d))
-          mv /tmp/$(basename $TOOLCHAIN .tar.xz)/${TOOLCHAIN_DIR_NAME} /tmp/
+          cd /tmp > /dev/null
+        	wget -nv -O release_page.html ${version_repo}/targets/x86/64/
+        	toolchain_file=$(grep -m 1 -Eo '"openwrt-toolchain-(.*).tar.xz"' /tmp/release_page.html | tr -d '"')
+        	echo 'Downloading toolchain...'
+        	wget -nv -O ${toolchain_file} ${version_repo}/targets/x86/64/${toolchain_file}
+        	tar -xf ${toolchain_file}
+        	toolchain_dir=$(basename $(find $(basename $toolchain_file .tar.xz) -name "toolchain-*" -type d))
+        	mv -f $(basename $toolchain_file .tar.xz)/${toolchain_dir} .
+        	toolchain_path=/tmp/$toolchain_dir
+        	rm -rf $(basename $toolchain_file .tar.xz)*
+        	cd - > /dev/null
           
           #Setup external toolchain
-          ./scripts/ext-toolchain.sh --toolchain /tmp/${TOOLCHAIN_DIR_NAME} --overwrite-config --config x86-64/generic
+          ./scripts/ext-toolchain.sh --toolchain $toolchain_path --overwrite-config --config x86-64/generic
           
       - name: Make download
         run: |
