Restore action runner

diff --git a/.github/workflows/openwrt-osm-ci.yml b/.github/workflows/openwrt-osm-ci.yml
--- a/.github/workflows/openwrt-osm-ci.yml
+++ b/.github/workflows/openwrt-osm-ci.yml
@@ -10,7 +10,7 @@ name: OpenWrt-OSM-CI
 
 on:
   workflow_dispatch:
-    branches: 
+    branches:
       - main
   release:
     types: [published]
@@ -21,12 +21,12 @@ jobs:
 
     name: Build OpenWrt OSM Firmware
 
-    runs-on: self-hosted
-    
+    runs-on: ubuntu-latest
+
     defaults:
         run:
           working-directory: ./openwrt
-          
+
     env:
       VERSION_NUMBER: ""
 
@@ -55,38 +55,38 @@ jobs:
           df -h
           echo "======================="
           du -h ./ --max-depth=1
-          
+
       - name: Download source code
         run: |
           #Prepare version
           source ../parse_yaml.sh
           eval $(parse_yaml ../version.yaml)
-          
+
           #Download source code
           rm -f .gitkeep
           git config --global advice.detachedHead false
           git clone -b $version_upstream_version_tag --depth 1 https://github.com/openwrt/openwrt.git .
-          
+
           # $1 repo url
           download_package(){
-          	repo=$(echo $1 | grep -Eo '^http*.*..git')
-          	commit=$(echo $1 | grep -Eo '\^.*' | tr -d '^')
-          	branch=$(echo $1 | grep -Eo ';.*' | tr -d ';')
-          	if [ ! -z $commit ]; then
-          		echo Downloading package from $1
-          		git -C package clone $repo && cd package/$(basename $repo .git) && git checkout $commit && cd -
-          	elif [ ! -z $branch ]; then
-          		echo Downloading package from $1
-          		git -C package clone $repo --depth 1 --branch $branch
-          	else
-          		echo "Invalid package info $1"
-          		exit 1
-          	fi
+            repo=$(echo $1 | grep -Eo '^http*.*..git')
+            commit=$(echo $1 | grep -Eo '\^.*' | tr -d '^')
+            branch=$(echo $1 | grep -Eo ';.*' | tr -d ';')
+            if [ ! -z $commit ]; then
+              echo Downloading package from $1
+              git -C package clone $repo && cd package/$(basename $repo .git) && git checkout $commit && cd -
+            elif [ ! -z $branch ]; then
+              echo Downloading package from $1
+              git -C package clone $repo --depth 1 --branch $branch
+            else
+              echo "Invalid package info $1"
+              exit 1
+            fi
           }
-          
+
           #Download extra package
           for f in $version_package_ ; do eval download_package \$${f} ; done
-          
+
       - name: Update feeds
         run: |
           ./scripts/feeds update -a
@@ -102,10 +102,10 @@ jobs:
           #Download upstream release config
           version_repo=$(grep -E '^VERSION_REPO.*https:/.' include/version.mk | grep -Eo 'https://.*[^)]')
           wget -nv -O .config $version_repo/targets/x86/64/config.buildinfo
-          
+
           #Merge config
           for f in $version_config_ ; do eval echo \$${f} >> .config ; done
-          
+
           #Set dnsmasq-full as default
           sed -i 's/dnsmasq \\/dnsmasq-full \\/g' include/target.mk
           #Config luci-theme-argon as default theme
@@ -114,7 +114,7 @@ jobs:
           sed -i "s/CONFIG_VERSION_DIST=\"OpenWrt\"/CONFIG_VERSION_DIST=\"OpenWrt-OSM\"/g" .config
           sed -i "s/CONFIG_VERSION_NUMBER=\"\"/CONFIG_VERSION_NUMBER=\"${version_version_number}\"/g" .config
           sed -i "s/CONFIG_VERSION_CODE=\"\"/CONFIG_VERSION_CODE=\"$(git -C ../ rev-parse --short=10 HEAD)\"/g" .config
-          
+
           #Download Toolchain
           cd /tmp > /dev/null
           wget -nv -O release_page.html ${version_repo}/targets/x86/64/
@@ -127,16 +127,16 @@ jobs:
           toolchain_path=/tmp/$toolchain_dir
           rm -rf $(basename $toolchain_file .tar.xz)*
           cd - > /dev/null
-          
+
           #Setup external toolchain
           ./scripts/ext-toolchain.sh --toolchain $toolchain_path --overwrite-config --config x86-64/generic
-          
+
       - name: Make download
         run: |
           make download -j8 || make download -j1 V=s
           rm -rf $(find ./dl/ -size -1024c)
           find ../patches/ -type f | while read patch; do cp $patch ${patch#*../patches/}; done
-          
+
       - name: Compile firmware
         run: |
           make -j$(nproc) || make -j1 V=s
@@ -152,15 +152,15 @@ jobs:
           #Convert img to vmdk
           for file in $(find ./bin -name "openwrt-osm-*-efi.img.gz" -type f);
           do
-          	echo "Convert image $(basename $file) to vmdk"
-          	cd $(dirname $file) > /dev/null
-          	gunzip -f -q -c $(basename $file) > $(basename $file .gz)
-          	qemu-img convert -f raw $(basename $file .gz) -O vmdk $(basename $file .img.gz).vmdk
-          	gzip -f -q $(basename $file .img.gz).vmdk
-          	rm $(basename $file .gz)
-          	cd - > /dev/null
+            echo "Convert image $(basename $file) to vmdk"
+            cd $(dirname $file) > /dev/null
+            gunzip -f -q -c $(basename $file) > $(basename $file .gz)
+            qemu-img convert -f raw $(basename $file .gz) -O vmdk $(basename $file .img.gz).vmdk
+            gzip -f -q $(basename $file .img.gz).vmdk
+            rm $(basename $file .gz)
+            cd - > /dev/null
           done
-          
+
       - name: Prepare artifact
         run: |
           mkdir -p ./artifact
